[package]
name = "automata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dfa"
path = "src/main.rs"

[profile.release]
lto = true

[dependencies]
itertools = "0.10.4"